<?php
// Trip-report deletion approval workflow.
//
// When a Dispatcher clicks Delete on a trip report row, we don't drop the
// dispatch immediately — we record a pending request here so an Admin or
// Dispatch Admin can approve (which performs the actual delete) or reject.
// Admin / Dispatch Admin delete clicks bypass approval (they ARE the approval).

if (!function_exists('td_ensure_table')) {
    function td_ensure_table(PDO $conn): void {
        static $ensured = false;
        if ($ensured) { return; }

        $conn->exec(
            "CREATE TABLE IF NOT EXISTS trip_report_deletion_request (
                tdr_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                d_id INTEGER NOT NULL,
                requested_by INTEGER NOT NULL,
                requested_by_name VARCHAR(200) NOT NULL DEFAULT '',
                requested_by_role VARCHAR(50) NOT NULL DEFAULT '',
                requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                status VARCHAR(20) NOT NULL DEFAULT 'pending',
                approved_by INTEGER NULL,
                approved_at TIMESTAMP NULL,
                rejection_reason VARCHAR(500) NOT NULL DEFAULT ''
            )"
        );
        $conn->exec("CREATE INDEX IF NOT EXISTS idx_tdr_dispatch ON trip_report_deletion_request (d_id)");
        $conn->exec("CREATE INDEX IF NOT EXISTS idx_tdr_status ON trip_report_deletion_request (status)");
        pt_mark_table_exists('trip_report_deletion_request', true);
        $ensured = true;
    }

    /**
     * Returns d_id => request_row for every PENDING deletion request.
     * Used by the table renderer so it can flip the action buttons.
     */
    function td_pending_by_dispatch(PDO $conn): array {
        td_ensure_table($conn);
        $stmt = $conn->query(
            "SELECT tdr_id, d_id, requested_by, requested_by_name, requested_by_role, requested_at
             FROM trip_report_deletion_request
             WHERE status = 'pending'"
        );
        $out = [];
        while ($r = $stmt->fetch()) {
            $out[(int)$r['d_id']] = $r;
        }
        return $out;
    }

    /**
     * Insert a new pending deletion request. If one already exists for this
     * d_id, we leave it alone and return false (no duplicate spam).
     */
    function td_create_request(PDO $conn, int $dId, int $userId, string $userName, string $userRole): bool {
        td_ensure_table($conn);
        $stmt = $conn->prepare(
            "SELECT 1 FROM trip_report_deletion_request
             WHERE d_id = ? AND status = 'pending' LIMIT 1"
        );
        $stmt->execute([$dId]);
        if ($stmt->fetchColumn()) { return false; }

        $stmt = $conn->prepare(
            "INSERT INTO trip_report_deletion_request
                (d_id, requested_by, requested_by_name, requested_by_role)
             VALUES (?, ?, ?, ?)"
        );
        $stmt->execute([$dId, $userId, $userName, $userRole]);
        return true;
    }

    /** Mark any pending request for this dispatch as approved by the given user. */
    function td_mark_approved(PDO $conn, int $dId, int $approverId): void {
        td_ensure_table($conn);
        $stmt = $conn->prepare(
            "UPDATE trip_report_deletion_request
             SET status = 'approved', approved_by = ?, approved_at = NOW()
             WHERE d_id = ? AND status = 'pending'"
        );
        $stmt->execute([$approverId, $dId]);
    }

    /** Mark a specific request as rejected. */
    function td_mark_rejected(PDO $conn, int $tdrId, int $approverId, string $reason): void {
        td_ensure_table($conn);
        $stmt = $conn->prepare(
            "UPDATE trip_report_deletion_request
             SET status = 'rejected', approved_by = ?, approved_at = NOW(), rejection_reason = ?
             WHERE tdr_id = ? AND status = 'pending'"
        );
        $stmt->execute([$approverId, $reason, $tdrId]);
    }
}
