<?php

// routes.php - Define available routes
$routes = [
    '' => 'admin/dashboard.php',
    'dashboard' => 'admin/dashboard.php',
    'dispatchDashboard' => 'admin/dashboard.php',
    // Phase 13 — tile-based dispatch board with drag-and-drop assign.
    'dispatchTiles' => 'admin/dispatch-tiles.php',
    // Phase 14 — container tracking (Pickup → On Trip → Delivered with live GPS).
    'containerTracking' => 'admin/container-tracking.php',
    'dashboard-trailer' => 'admin/dashboard-trailer.php',
    'dashboard-truck' => 'admin/dashboard-truck.php',
    'dashboard-attendance' => 'admin/dashboard-attendance.php',
    'dispatch' => 'admin/dispatch.php',
    'driversReport' => 'admin/drivers-report.php',
    'drivers' => 'admin/drivers.php',
    'print' => 'admin/print_dispatch.php',
    'printcth' => 'admin/print_dispatchCTH.php',
    'printDriverRegistration' => 'admin/print_driver_registration.php',
    'coupon' => 'admin/coupon.php',
    // Public, no-login transaction view reached by scanning a coupon QR.
    'coupon-view' => 'coupon-view.php',
    'gate' => 'admin/gate.php',
    'mybook' => 'admin/mybooking.php',
    'allbook' => 'admin/allbooking.php',
    'addbook' => 'admin/addbooking.php',
    'multibook' => 'admin/multibooking.php',
    'monitoring' => 'admin/monitoring.php',
    'abcmonitoring' => 'admin/abcmonitoring.php',
    'dolemonitoring' => 'admin/dolemonitoring.php',
    'dmmonitoring' => 'admin/dmmonitoring.php',
    'farmmonitoring' => 'admin/farmmonitoring.php',
    'sumimonitoring' => 'admin/sumimonitoring.php',
    'cthmonitoring' => 'admin/cthmonitoring.php',
    'trailer' => 'admin/trailer.php',
    'tripReport' => 'admin/trip-report.php',
    'attendReport' => 'admin/attend-report.php',
    'trailerReport' => 'admin/trailer-report.php',
    'truckReport' => 'admin/truck-report.php',
    'truck' => 'admin/truck.php',
    'geotab-connection' => 'admin/geotab-connection.php',
    'geotab-devices' => 'admin/geotab-devices.php',
    'geotab-zones' => 'admin/geotab-zones.php',
    'geotab-faults' => 'admin/geotab-faults.php',
    'fuel-reconciliation' => 'admin/fuel-reconciliation.php',
    'geotab-behavior' => 'admin/geotab-behavior.php',
    'unitProfile' => 'admin/addunit-page.php',
    'unitEditProfile' => 'admin/updateunit-page.php',
    'containerMonitoring' => 'admin/container_monitoring.php',
    'genset' => 'admin/genset.php',
    'user' => 'admin/user.php',
    'segment' => 'admin/segment.php',
    'settings' => 'admin/settings.php',
    'activityLog' => 'admin/activity-log.php',
    'tripRates' => 'admin/trip-rates.php',
    'foulTrips' => 'admin/foul-trips.php',
    'payroll' => 'admin/payroll.php',
    'bookingSegments' => 'admin/booking-segments.php',
    'incidents' => 'admin/incidents.php',
    'billing' => 'admin/billing.php',
    'workflow' => 'admin/workflow.php',
    'fieldCaptures' => 'admin/field-captures.php',
    'dispatchReceipts' => 'admin/dispatch-receipts.php',
    'verifications' => 'admin/verifications.php',
    'equipment' => 'admin/equipment.php',
    'equipmentUtil' => 'admin/equipment-utilization.php',
    'serviceTrips' => 'admin/service-trips.php',
    'chat' => 'admin/chat.php',
    'blocked-units' => 'admin/blocked-units.php',
    // Executive overview — truck search + current trip, ops prediction,
    // completed-trip trend, customer ranking (mobile-first).
    'executive' => 'admin/executive.php',
    'profile' => 'admin/profile.php',
    'logout' => 'logout.php',
    'login' => 'login.php',
    'index' => 'login.php',
    // Microsoft (Entra ID) SSO — start + callback.
    'ms-login'    => 'php/operations/ms_sso_start.php',
    'ms-callback' => 'php/operations/ms_sso_callback.php',
    // Dispatcher routes
    'dispatch-dashboard' => 'dispatcher/dashboard.php',
    'dispatch-admin-dashboard' => 'dispatcher/dispatch-admin-dashboard.php',
    'dispatch-admin-analytics' => 'dispatcher/dispatch-admin-analytics.php',
    'dispatch-dispatchDashboard' => 'dispatcher/dashboard.php',
    // Phase 13 — tile-based dispatch board with drag-and-drop assign.
    'dispatch-tiles' => 'dispatcher/dispatch-tiles.php',
    // Phase 14 — container tracking (Pickup → On Trip → Delivered with live GPS).
    'dispatch-tracking' => 'dispatcher/container-tracking.php',
    'dispatch-dashboard-trailer' => 'dispatcher/dashboard-trailer.php',
    'dispatch-dashboard-truck' => 'dispatcher/dashboard-truck.php',
    'dispatch-dashboard-attendance' => 'dispatcher/dashboard-attendance.php',
    'dispatch-dispatch' => 'dispatcher/dispatch.php',
    'dispatch-dispatchTest' => 'dispatcher/dispatch-test.php',
    'dispatch-driversReport' => 'dispatcher/drivers-report.php',
    'dispatch-drivers' => 'dispatcher/drivers.php',
    'dispatch-violations' => 'dispatcher/violations.php',
    'dispatch-print' => 'dispatcher/print_dispatch.php',
    'dispatch-print1' => 'dispatcher/print_dispatch1.php',
    'dispatch-printJob' => 'dispatcher/print_job_ticket.php',
    'dispatch-printcth' => 'dispatcher/print_dispatchCTH.php',
    'dispatch-printDriverRegistration' => 'dispatcher/print_driver_registration.php',
    'dispatch-coupon' => 'dispatcher/coupon.php',
    'print_dispatch_receipt' => 'dispatcher/print_dispatch_receipt.php',
    'dispatch-gate' => 'dispatcher/gate.php',
    'dispatch-mybook' => 'dispatcher/mybooking.php',
    'dispatch-allbook' => 'dispatcher/allbooking.php',
    'dispatch-addbook' => 'dispatcher/addbooking.php',
    'dispatch-multibook' => 'dispatcher/multibooking.php',
    'dispatch-monitoring' => 'dispatcher/monitoring.php',
    'dispatch-abcmonitoring' => 'dispatcher/abcmonitoring.php',
    'dispatch-dolemonitoring' => 'dispatcher/dolemonitoring.php',
    'dispatch-dmmonitoring' => 'dispatcher/dmmonitoring.php',
    'dispatch-farmmonitoring' => 'dispatcher/farmmonitoring.php',
    'dispatch-sumimonitoring' => 'dispatcher/sumimonitoring.php',
    'dispatch-cthmonitoring' => 'dispatcher/cthmonitoring.php',
    'dispatch-trailer' => 'dispatcher/trailer.php',
    'dispatch-tripReport' => 'dispatcher/trip-report.php',
    'dispatch-attendReport' => 'dispatcher/attend-report.php',
    'dispatch-trailerReport' => 'dispatcher/trailer-report.php',
    'dispatch-truckReport' => 'dispatcher/truck-report.php',
    'dispatch-truck' => 'dispatcher/truck.php',
    'dispatch-unitProfile' => 'dispatcher/addunit-page.php',
    'dispatch-unitEditProfile' => 'dispatcher/updateunit-page.php',
    'dispatch-containerMonitoring' => 'dispatcher/container_monitoring.php',
    'dispatch-genset' => 'dispatcher/genset.php',
    'dispatch-user' => 'dispatcher/user.php',
    'dispatch-segment' => 'dispatcher/segment.php',
    'dispatch-bookingSegments' => 'dispatcher/booking-segments.php',
    'dispatch-incidents' => 'dispatcher/incidents.php',
    'dispatch-billing' => 'dispatcher/billing.php',
    'dispatch-workflow' => 'dispatcher/workflow.php',
    'dispatch-fieldCaptures' => 'dispatcher/field-captures.php',
    'dispatch-receipts' => 'dispatcher/dispatch-receipts.php',
    'dispatch-verifications' => 'dispatcher/verifications.php',
    'dispatch-foulTrips' => 'dispatcher/foul-trips.php',
    'dispatch-equipment' => 'dispatcher/equipment.php',
    'dispatch-equipmentUtil' => 'dispatcher/equipment-utilization.php',
    'dispatch-serviceTrips' => 'dispatcher/service-trips.php',
    'dispatch-addEquipment' => 'dispatcher/add-equipment.php',
    'dispatch-chat' => 'dispatcher/chat.php',
    'dispatch-blocked-units' => 'dispatcher/blocked-units.php',
    'dispatch-manageBlockedTrucks' => 'dispatcher/manage-blocked-trucks.php',
    'dispatch-profile' => 'dispatcher/profile.php',
    // Gastender (Fuel Ticketing) routes — Phase 13
    'gas-ticketing'   => 'gas/ticketing.php',
    'gas-inventory'   => 'gas/fuel-inventory.php',
    'gas-report'      => 'gas/msReport.php',
    'gas-codes'       => 'gas/ticket-codes.php',
    'gas-profile'     => 'gas/profile.php',
    'gas-logout'      => 'logout.php',
    'gas-login'       => 'login.php',
    // Payroll routes — piece-rate assignment via coupon control number.
    'payroll-dashboard' => 'payroll/dashboard.php',
    'payroll-profile'   => 'payroll/profile.php',
    'payroll-logout'    => 'logout.php',
    'payroll-login'     => 'login.php',
    // Gate-Guard routes
    'gate-dashboard' => 'gate/dashboard.php',
    'gate-checkin'   => 'gate/checkin.php',
    'gate-incident'  => 'gate/incident.php',
    'gate-profile'   => 'gate/profile.php',
    'gate-logout'    => 'logout.php',
    'gate-login'     => 'login.php',
    // Maintenance role routes
    'maintenance-dashboard' => 'maintenance/dashboard.php',
    'maintenance-units'     => 'maintenance/units.php',
    'maintenance-history'   => 'maintenance/history.php',
    'maintenance-profile'   => 'maintenance/profile.php',
    'maintenance-logout'    => 'logout.php',
    'maintenance-login'     => 'login.php',
    // Phase 12 — Client portal routes
    'client-dashboard'  => 'client/dashboard.php',
    'client-book'       => 'client/book-trip.php',
    'client-book-cth'   => 'client/book-trip-cth.php',
    'client-mybookings' => 'client/my-bookings.php',
    'client-profile'    => 'client/profile.php',
    'client-logout'     => 'logout.php',
    'client-login'      => 'login.php',
    'dispatch-logout' => 'logout.php',
    'dispatch-login'  => 'login.php',
    // Driver routes
    'driver-logout'   => 'logout.php',
    'driver-login'    => 'login.php',
    'driver-dashboard' => 'driver/dashboard.php',
    'driver-profile' => 'driver/profile.php',
    'driver-bookinglist' => 'driver/bookinglist.php',
    'driver-unit' => 'driver/unit.php',
    'driver-tripReport' => 'driver/trip-report.php',
    'driver-driversReport' => 'driver/drivers-report.php',
    // Phase 5 — Driver PWA
    'driver-checklist' => 'driver/checklist.php',
    'driver-pod' => 'driver/pod.php',
    'driver-gateless' => 'driver/gateless.php',
    'driver-jackup' => 'driver/jackup.php',
    'driver-hustling' => 'driver/hustling.php',
    'driver-breakdown' => 'driver/breakdown.php',
    'driver-messages' => 'driver/messages.php',
    // Phase 6 — Driver receipts
    'driver-receipts' => 'driver/receipts.php',
    // Driver self-earnings (piece-rate based)
    'driver-earnings' => 'driver/earnings.php',
    'driver-payrollHistory' => 'driver/payroll-history.php',
    // Shop routes
    'shop-dashboard' => 'shop/dashboard.php',
    'shop-rescue' => 'shop/rescue.php',
    'shop-shop' => 'shop/shop.php',
    'shop-manpower' => 'shop/manpower.php',
    'shop-rescueReport' => 'shop/rescue-report.php',
    'shop-shopReport' => 'shop/shop-report.php',
    'shop-profile' => 'shop/profile.php',
    // HR (User) routes
    'hr-logout'    => 'logout.php',
    'hr-login'     => 'login.php',
    'hr-dashboard' => 'HR/dashboard.php',
    'hr-profile' => 'HR/profile.php',
    'hr-drivers' => 'HR/drivers.php',
    'hr-performance' => 'HR/performance.php',
    'hr-violationReport' => 'HR/violationReport.php',
    'hr-tripReport' => 'HR/trip-report.php',
    'hr-attendReport' => 'HR/attend-report.php',
    // HR Admin routes
    'hra-dashboard' => 'HR Admin/dashboard.php',
    'hra-profile' => 'HR Admin/profile.php',
    'hra-drivers' => 'HR Admin/drivers.php',
    'hra-performance' => 'HR Admin/performance.php',
    'hra-performanceDriver' => 'HR Admin/performance-driver.php',
    'hra-payroll' => 'HR Admin/payroll.php',
    'hra-violationReport' => 'HR Admin/violationReport.php',
    'hra-violationDriver' => 'HR Admin/violation-driver.php',
    'hra-tripReport' => 'HR Admin/trip-report.php',
    'hra-attendReport' => 'HR Admin/attend-report.php',
    // Visual routes
    'visual-dashboard' => 'data-visual/dashboard.php',
    'visual-profile' => 'data-visual/profile.php',
    'visual-performance' => 'data-visual/performance.php',
    'visual-performanceDriver' => 'data-visual/performance-driver.php',
    'visual-violationReport' => 'data-visual/violationReport.php',
    'visual-violationDriver' => 'data-visual/violation-driver.php',
    'visual-truckReport' => 'data-visual/truck-report.php',
    'visual-trailerReport' => 'data-visual/trailer-report.php',
];

// Get the route from URL
$route = $_GET['route'] ?? 'dashboard';

// Check if the route exists, otherwise show a 404 page
if (array_key_exists($route, $routes)) {
    require $routes[$route];
} else {
    require 'admin/404.php';
}
?>
