-- =====================================================================
-- Base schema for Fleet Management (auto-converted from MySQL dump).
-- Generated by php/config/convert_schema.php
-- Idempotent: uses CREATE TABLE IF NOT EXISTS and CREATE INDEX IF NOT EXISTS.
-- =====================================================================

CREATE TABLE IF NOT EXISTS assign_manpower (
    am_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rr_id INTEGER NOT NULL,
    sr_id INTEGER NOT NULL,
    smp_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
    booking_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_no VARCHAR(200) NOT NULL,
    booking_type VARCHAR(20) NOT NULL DEFAULT 'Local',
    booking_sn VARCHAR(200) NOT NULL,
    booking_do VARCHAR(200) NOT NULL,
    booking_date DATE NOT NULL,
    booking_daterequired DATE NOT NULL,
    booking_haulingstartdate DATE NOT NULL,
    booking_lastdatestorage DATE NOT NULL,
    booking_lastdatedemurrage DATE NOT NULL,
    booking_lastdatedetention DATE NOT NULL,
    costumer VARCHAR(200) NOT NULL,
    customer_segment VARCHAR(50) NOT NULL DEFAULT '',
    container_seal VARCHAR(200) NOT NULL,
    container VARCHAR(200) NOT NULL,
    booking_activity VARCHAR(200) NOT NULL,
    container_status VARCHAR(200) NOT NULL,
    hauling_segment VARCHAR(200) NOT NULL,
    hauling_type VARCHAR(200) NOT NULL,
    trip_from VARCHAR(200) NOT NULL,
    trip_to VARCHAR(200) NOT NULL,
    return_location VARCHAR(200) NOT NULL,
    vessel_name VARCHAR(150) NOT NULL DEFAULT '',
    voyage_no VARCHAR(100) NOT NULL DEFAULT '',
    container_no_port VARCHAR(100) NOT NULL DEFAULT '',
    bill_of_lading VARCHAR(100) NOT NULL DEFAULT '',
    port_location VARCHAR(150) NOT NULL DEFAULT '',
    customs_cleared BOOLEAN NOT NULL DEFAULT FALSE,
    customs_cleared_at TIMESTAMP DEFAULT NULL,
    client_notified_at TIMESTAMP DEFAULT NULL,
    quantity INTEGER NOT NULL,
    quantity_use INTEGER NOT NULL,
    status VARCHAR(200) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_booking_customer_segment ON booking (customer_segment);

CREATE TABLE IF NOT EXISTS cache (
    "key" VARCHAR(255) NOT NULL,
    "value" TEXT NOT NULL,
    expiration INTEGER NOT NULL,
    PRIMARY KEY ("key")
);
CREATE INDEX IF NOT EXISTS cache_expiration_index ON cache (expiration);

CREATE TABLE IF NOT EXISTS cache_locks (
    "key" VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    expiration INTEGER NOT NULL,
    PRIMARY KEY ("key")
);
CREATE INDEX IF NOT EXISTS cache_locks_expiration_index ON cache_locks (expiration);

CREATE TABLE IF NOT EXISTS consume_fuel (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    unit VARCHAR(200) NOT NULL,
    driver VARCHAR(200) NOT NULL DEFAULT '',
    hubo NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    consumeltr NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    "date" TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_consume_fuel_unit ON consume_fuel (unit);
CREATE INDEX IF NOT EXISTS idx_consume_fuel_date ON consume_fuel ("date");

CREATE TABLE IF NOT EXISTS container_activity (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    container_name VARCHAR(200) NOT NULL,
    container_location VARCHAR(200) NOT NULL,
    truck_no VARCHAR(200) NOT NULL,
    trailer_no VARCHAR(200) NOT NULL,
    genset_no VARCHAR(200) NOT NULL,
    driver_name VARCHAR(200) NOT NULL,
    container_status VARCHAR(200) NOT NULL,
    trip_status VARCHAR(200) NOT NULL,
    "date" TIMESTAMP NOT NULL,
    remarks VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS container_monitoring (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    container_number VARCHAR(50) NOT NULL,
    shipping_line VARCHAR(50) DEFAULT NULL,
    location_tag VARCHAR(100) DEFAULT NULL,
    status VARCHAR(100) NOT NULL DEFAULT 'pending',
    priority VARCHAR(100) NOT NULL DEFAULT 'medium',
    pm_number VARCHAR(50) DEFAULT NULL,
    reference VARCHAR(100) DEFAULT NULL,
    tr_gs VARCHAR(50) DEFAULT NULL,
    driver_name VARCHAR(150) DEFAULT NULL,
    driver_contact VARCHAR(100) DEFAULT NULL,
    driver_id INTEGER DEFAULT NULL,
    etd TIMESTAMP DEFAULT NULL,
    cy_arrival TIMESTAMP DEFAULT NULL,
    cy_departure TIMESTAMP DEFAULT NULL,
    ph_arrival TIMESTAMP DEFAULT NULL,
    ptsi TIMESTAMP DEFAULT NULL,
    seal_number VARCHAR(50) DEFAULT NULL,
    vessel_etd TIMESTAMP DEFAULT NULL,
    week_of_year SMALLINT DEFAULT NULL,
    last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stage VARCHAR(200) NOT NULL,
    remarks VARCHAR(200) NOT NULL
);
CREATE INDEX IF NOT EXISTS container_number ON container_monitoring (container_number);
CREATE INDEX IF NOT EXISTS status ON container_monitoring (status);
CREATE INDEX IF NOT EXISTS shipping_line ON container_monitoring (shipping_line);

CREATE TABLE IF NOT EXISTS customer (
    customer_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(200) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    customer_segment VARCHAR(50) NOT NULL DEFAULT '',
    notify_email VARCHAR(255) NOT NULL DEFAULT '',
    notify_phone VARCHAR(50) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_customer_segment ON customer (customer_segment);

CREATE TABLE IF NOT EXISTS dispatch (
    d_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    booking_no VARCHAR(200) NOT NULL,
    dispatch_ref VARCHAR(160) NOT NULL DEFAULT '',
    booking_sn VARCHAR(200) NOT NULL,
    booking_do VARCHAR(200) NOT NULL,
    cth_broker VARCHAR(200) NOT NULL,
    cth_eirout VARCHAR(200) NOT NULL,
    cth_eirin VARCHAR(255) NOT NULL DEFAULT '',
    d_datetime TIMESTAMP NOT NULL,
    d_dispatcher VARCHAR(200) NOT NULL,
    d_dispatchhub VARCHAR(200) NOT NULL,
    d_drivername VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    d_truck VARCHAR(200) NOT NULL,
    d_trailer VARCHAR(200) NOT NULL,
    d_genset VARCHAR(200) NOT NULL,
    d_tripreceipt VARCHAR(200) NOT NULL,
    d_ecs VARCHAR(200) NOT NULL,
    costumer VARCHAR(200) NOT NULL,
    workflow_stage VARCHAR(40) NOT NULL DEFAULT 'dispatcher_assigned',
    workflow_updated_at TIMESTAMP DEFAULT NULL,
    driver_accepted_at TIMESTAMP DEFAULT NULL,
    driver_declined_at TIMESTAMP DEFAULT NULL,
    decline_reason VARCHAR(255) NOT NULL DEFAULT '',
    gate_cleared_at TIMESTAMP DEFAULT NULL,
    billing_closed_at TIMESTAMP DEFAULT NULL,
    client_notified_at TIMESTAMP DEFAULT NULL,
    billing_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    billing_currency VARCHAR(10) NOT NULL DEFAULT 'PHP',
    billing_notes VARCHAR(500) NOT NULL DEFAULT '',
    trip_started_at TIMESTAMP DEFAULT NULL,
    trip_completed_at TIMESTAMP DEFAULT NULL,
    verified_by INTEGER DEFAULT NULL,
    verified_at TIMESTAMP DEFAULT NULL,
    verification_notes VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS dispatch_receipt (
    dr_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER NOT NULL,
    receipt_type VARCHAR(50) NOT NULL DEFAULT 'other',
    title VARCHAR(150) NOT NULL DEFAULT '',
    file_path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL DEFAULT '',
    requires_ack BOOLEAN NOT NULL DEFAULT TRUE,
    attached_by INTEGER DEFAULT NULL,
    attached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dr_dispatch ON dispatch_receipt (d_id);

CREATE TABLE IF NOT EXISTS drivers (
    driver_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_idnumber INTEGER NOT NULL,
    driver_rfid VARCHAR(200) NOT NULL,
    driver_fname VARCHAR(200) NOT NULL,
    driver_mname VARCHAR(200) NOT NULL,
    driver_lname VARCHAR(200) NOT NULL,
    driver_contact VARCHAR(200) NOT NULL,
    driver_image VARCHAR(200) NOT NULL,
    driver_signature VARCHAR(255) NOT NULL,
    driver_assignunit VARCHAR(200) NOT NULL,
    driver_assignsegment VARCHAR(200) NOT NULL,
    driver_assignbase VARCHAR(200) NOT NULL,
    driver_status VARCHAR(200) NOT NULL,
    driver_email VARCHAR(200) NOT NULL,
    driver_uname VARCHAR(200) NOT NULL,
    driver_pass VARCHAR(255) NOT NULL,
    driver_account_status VARCHAR(200) NOT NULL,
    shift_truck VARCHAR(50) NOT NULL DEFAULT '',
    shift_started_at TIMESTAMP DEFAULT NULL,
    shift_ended_at TIMESTAMP DEFAULT NULL,
    last_seen_at TIMESTAMP DEFAULT NULL,
    last_lat NUMERIC(10,7) DEFAULT NULL,
    last_lng NUMERIC(10,7) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS drivers_attendance (
    da_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    da_controlno VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    da_status VARCHAR(200) NOT NULL,
    da_remarks VARCHAR(200) NOT NULL,
    da_timein TIMESTAMP NOT NULL,
    da_timeout TIMESTAMP NOT NULL,
    da_date DATE NOT NULL,
    vl_sl_dateprepared DATE NOT NULL,
    vl_sl_datestart DATE NOT NULL,
    vl_sl_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS driver_shift (
    ds_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL,
    truck_code VARCHAR(50) NOT NULL DEFAULT '',
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP DEFAULT NULL,
    machine_hours NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    pdc_id INTEGER DEFAULT NULL,
    notes VARCHAR(255) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_ds_driver_open ON driver_shift (driver_id, ended_at);
CREATE INDEX IF NOT EXISTS idx_ds_truck ON driver_shift (truck_code);

CREATE TABLE IF NOT EXISTS failed_jobs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    connection TEXT NOT NULL,
    queue TEXT NOT NULL,
    payload TEXT NOT NULL,
    exception TEXT NOT NULL,
    failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS failed_jobs_uuid_unique ON failed_jobs (uuid);

CREATE TABLE IF NOT EXISTS fuel_inventory (
    fi_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fi_pono VARCHAR(200) NOT NULL DEFAULT '',
    fi_noofliters NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    fi_receiveby VARCHAR(200) NOT NULL DEFAULT '',
    fi_date TIMESTAMP NOT NULL,
    fi_invo VARCHAR(200) NOT NULL DEFAULT '',
    fi_plateno VARCHAR(200) NOT NULL DEFAULT '',
    fi_consumableltr NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    fi_consumeltr NUMERIC(11,2) NOT NULL DEFAULT 0.00
);
CREATE INDEX IF NOT EXISTS idx_fuel_inventory_date ON fuel_inventory (fi_date);
CREATE INDEX IF NOT EXISTS idx_fuel_inventory_consumable ON fuel_inventory (fi_consumableltr);

CREATE TABLE IF NOT EXISTS fuel_report (
    f_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    f_date TIMESTAMP NOT NULL,
    f_unit VARCHAR(200) NOT NULL,
    f_lasthubo NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_hubo NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    calculated_hubo NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_kmrun NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_nooflit NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_actratio NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_driver VARCHAR(200) NOT NULL DEFAULT '',
    f_driverid VARCHAR(50) NOT NULL DEFAULT '',
    f_stdratio NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_excess_saving NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_hourmeter VARCHAR(200) NOT NULL DEFAULT '0',
    f_controlno VARCHAR(255) NOT NULL,
    f_idenolt NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    f_tripticket VARCHAR(200) NOT NULL DEFAULT '',
    f_tripsegment VARCHAR(200) NOT NULL DEFAULT '',
    f_trasactionby VARCHAR(200) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_fuel_report_controlNo ON fuel_report (f_controlno);
CREATE INDEX IF NOT EXISTS idx_fuel_report_unit_date ON fuel_report (f_unit, f_date);
CREATE INDEX IF NOT EXISTS idx_fuel_report_driverId ON fuel_report (f_driverid);

CREATE TABLE IF NOT EXISTS gateless_completion (
    gc_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER NOT NULL,
    trip_id INTEGER DEFAULT NULL,
    driver_id INTEGER NOT NULL,
    lat NUMERIC(10,7) NOT NULL,
    lng NUMERIC(10,7) NOT NULL,
    accuracy_m INTEGER NOT NULL DEFAULT 0,
    photo1_path VARCHAR(255) NOT NULL DEFAULT '',
    photo2_path VARCHAR(255) NOT NULL DEFAULT '',
    captured_at TIMESTAMP NOT NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    offline BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_gc_dispatch ON gateless_completion (d_id);

CREATE TABLE IF NOT EXISTS gate_log (
    gl_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER DEFAULT NULL,
    direction VARCHAR(10) NOT NULL,
    truck_plate VARCHAR(50) NOT NULL DEFAULT '',
    trailer_code VARCHAR(50) NOT NULL DEFAULT '',
    genset_code VARCHAR(50) NOT NULL DEFAULT '',
    driver_id INTEGER DEFAULT NULL,
    qr_payload VARCHAR(255) NOT NULL DEFAULT '',
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    mismatch_reason VARCHAR(255) NOT NULL DEFAULT '',
    authorised BOOLEAN NOT NULL DEFAULT FALSE,
    guard_user_id INTEGER DEFAULT NULL,
    logged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gate_log_dispatch ON gate_log (d_id);
CREATE INDEX IF NOT EXISTS idx_gate_log_logged_at ON gate_log (logged_at);

CREATE TABLE IF NOT EXISTS gate_queue (
    gq_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER DEFAULT NULL,
    truck_plate VARCHAR(50) NOT NULL DEFAULT '',
    driver_id INTEGER DEFAULT NULL,
    direction VARCHAR(10) NOT NULL DEFAULT 'IN',
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP DEFAULT NULL,
    decision VARCHAR(20) NOT NULL DEFAULT 'pending',
    decided_by INTEGER DEFAULT NULL,
    notes VARCHAR(255) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_gate_queue_decision ON gate_queue (decision);

CREATE TABLE IF NOT EXISTS hauling (
    hauling_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    hauling_segment VARCHAR(200) NOT NULL,
    hauling_type VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS hustling_record (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_name VARCHAR(100) NOT NULL,
    shift VARCHAR(50) DEFAULT NULL,
    units VARCHAR(50) DEFAULT NULL,
    trailer_number VARCHAR(50) DEFAULT NULL,
    time_in TIME NOT NULL,
    time_out TIME NOT NULL,
    signature TEXT DEFAULT NULL,
    xray INTEGER DEFAULT 0,
    latag INTEGER DEFAULT 0,
    inspection INTEGER DEFAULT 0,
    ecd_on_dock INTEGER DEFAULT 0,
    total_trips INTEGER DEFAULT 0,
    remarks TEXT DEFAULT NULL,
    recorded_by VARCHAR(200) NOT NULL,
    modified_by VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS incident (
    inc_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER DEFAULT NULL,
    trip_id INTEGER DEFAULT NULL,
    driver_id INTEGER DEFAULT NULL,
    incident_type VARCHAR(40) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'low',
    description TEXT NOT NULL,
    lat NUMERIC(10,7) DEFAULT NULL,
    lng NUMERIC(10,7) DEFAULT NULL,
    photo_path VARCHAR(255) NOT NULL DEFAULT '',
    assistance VARCHAR(40) NOT NULL DEFAULT '',
    reassigned_d_id INTEGER DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    reported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_incident_dispatch ON incident (d_id);
CREATE INDEX IF NOT EXISTS idx_incident_status ON incident (status);

CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    queue VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    attempts SMALLINT NOT NULL,
    reserved_at INTEGER DEFAULT NULL,
    available_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS jobs_queue_index ON jobs (queue);

CREATE TABLE IF NOT EXISTS job_batches (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    total_jobs INTEGER NOT NULL,
    pending_jobs INTEGER NOT NULL,
    failed_jobs INTEGER NOT NULL,
    failed_job_ids TEXT NOT NULL,
    options TEXT DEFAULT NULL,
    cancelled_at INTEGER DEFAULT NULL,
    created_at INTEGER NOT NULL,
    finished_at INTEGER DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS location (
    location_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(200) NOT NULL,
    latitude VARCHAR(255) NOT NULL,
    longitude VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS message (
    msg_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    from_role VARCHAR(20) NOT NULL,
    from_id INTEGER NOT NULL,
    to_role VARCHAR(20) NOT NULL,
    to_id INTEGER DEFAULT NULL,
    body TEXT NOT NULL,
    d_id INTEGER DEFAULT NULL,
    read_at TIMESTAMP DEFAULT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_msg_to ON message (to_role, to_id, read_at);
CREATE INDEX IF NOT EXISTS idx_msg_dispatch ON message (d_id);

CREATE TABLE IF NOT EXISTS migrations (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    migration VARCHAR(255) NOT NULL,
    batch INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS outin (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    drivers_name VARCHAR(200) NOT NULL,
    truck_name VARCHAR(200) NOT NULL,
    trailer_name VARCHAR(200) NOT NULL,
    genset_name VARCHAR(200) NOT NULL,
    segment_trip VARCHAR(200) NOT NULL,
    "date" DATE NOT NULL,
    "time" TIME NOT NULL,
    status VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS pickup_capture (
    pc_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER NOT NULL,
    trip_id INTEGER NOT NULL,
    driver_id INTEGER NOT NULL,
    driver_id_number VARCHAR(100) NOT NULL DEFAULT '',
    container_no VARCHAR(100) NOT NULL,
    photo_path VARCHAR(255) NOT NULL,
    lat NUMERIC(10,7) DEFAULT NULL,
    lng NUMERIC(10,7) DEFAULT NULL,
    captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_pickup_capture_dispatch ON pickup_capture (d_id);
CREATE INDEX IF NOT EXISTS idx_pickup_capture_trip ON pickup_capture (trip_id);

CREATE TABLE IF NOT EXISTS pod_capture (
    pod_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER NOT NULL,
    trip_id INTEGER DEFAULT NULL,
    driver_id INTEGER NOT NULL,
    photo1_path VARCHAR(255) NOT NULL DEFAULT '',
    photo2_path VARCHAR(255) NOT NULL DEFAULT '',
    photo3_path VARCHAR(255) NOT NULL DEFAULT '',
    signature_path VARCHAR(255) NOT NULL DEFAULT '',
    signed_by VARCHAR(150) NOT NULL DEFAULT '',
    lat NUMERIC(10,7) DEFAULT NULL,
    lng NUMERIC(10,7) DEFAULT NULL,
    captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_by INTEGER DEFAULT NULL,
    verified_at TIMESTAMP DEFAULT NULL,
    verification_notes VARCHAR(500) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_pod_dispatch ON pod_capture (d_id);

CREATE TABLE IF NOT EXISTS pre_departure_checklist (
    pdc_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL,
    truck_code VARCHAR(50) NOT NULL DEFAULT '',
    trailer_code VARCHAR(50) NOT NULL DEFAULT '',
    genset_code VARCHAR(50) NOT NULL DEFAULT '',
    fuel_ok BOOLEAN NOT NULL DEFAULT FALSE,
    tyres_ok BOOLEAN NOT NULL DEFAULT FALSE,
    lights_ok BOOLEAN NOT NULL DEFAULT FALSE,
    cargo_area_ok BOOLEAN NOT NULL DEFAULT FALSE,
    genset_ok BOOLEAN NOT NULL DEFAULT FALSE,
    remarks VARCHAR(255) NOT NULL DEFAULT '',
    signed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_pdc_driver_time ON pre_departure_checklist (driver_id, signed_at);

CREATE TABLE IF NOT EXISTS push_send_log (
    psl_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    to_role VARCHAR(20) NOT NULL,
    to_id INTEGER DEFAULT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT 'webpush',
    subject VARCHAR(200) NOT NULL DEFAULT '',
    body VARCHAR(1000) NOT NULL DEFAULT '',
    d_id INTEGER DEFAULT NULL,
    outcome VARCHAR(50) NOT NULL DEFAULT 'queued',
    error VARCHAR(500) NOT NULL DEFAULT '',
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_psl_dispatch ON push_send_log (d_id);
CREATE INDEX IF NOT EXISTS idx_psl_outcome ON push_send_log (outcome);

CREATE TABLE IF NOT EXISTS push_subscription (
    ps_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL,
    endpoint VARCHAR(500) NOT NULL,
    p256dh_key VARCHAR(255) NOT NULL,
    auth_key VARCHAR(255) NOT NULL,
    user_agent VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_endpoint ON push_subscription (endpoint);
CREATE INDEX IF NOT EXISTS idx_ps_driver ON push_subscription (driver_id);

CREATE TABLE IF NOT EXISTS receipt_acknowledge (
    ra_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dr_id INTEGER NOT NULL,
    driver_id INTEGER NOT NULL,
    acknowledged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_ra_driver_receipt ON receipt_acknowledge (dr_id, driver_id);

CREATE TABLE IF NOT EXISTS reefer_monitoring (
    monitoring_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    segment VARCHAR(200) NOT NULL,
    van_number VARCHAR(20) DEFAULT NULL,
    pm_number VARCHAR(20) DEFAULT NULL,
    etd_date DATE DEFAULT NULL,
    cy_arrival_date DATE DEFAULT NULL,
    cy_arrival_time TIME DEFAULT NULL,
    cy_departure_date DATE DEFAULT NULL,
    cy_departure_time TIME DEFAULT NULL,
    ph_arrival_date DATE DEFAULT NULL,
    ph_arrival_time TIME DEFAULT NULL,
    cir VARCHAR(50) DEFAULT NULL,
    departure_ptsi_date DATE DEFAULT NULL,
    departure_ptsi_time TIME DEFAULT NULL,
    week VARCHAR(10) DEFAULT NULL,
    vessel_etd_date DATE DEFAULT NULL,
    customer_reference VARCHAR(50) DEFAULT NULL,
    remarks TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rescue_record (
    rr_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    r_id INTEGER NOT NULL,
    r_description VARCHAR(200) NOT NULL,
    r_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS rescue_unit (
    r_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    r_unit VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    r_startdatetime TIMESTAMP NOT NULL,
    r_enddatetime TIMESTAMP NOT NULL,
    r_km VARCHAR(200) NOT NULL,
    r_status VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(255) NOT NULL,
    user_id BIGINT DEFAULT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    user_agent TEXT DEFAULT NULL,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sessions_user_id_index ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_last_activity_index ON sessions (last_activity);

CREATE TABLE IF NOT EXISTS shop_manpower (
    smp_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    smp_fname VARCHAR(200) NOT NULL,
    smp_mname VARCHAR(200) NOT NULL,
    smp_lname VARCHAR(200) NOT NULL,
    smp_role VARCHAR(200) NOT NULL,
    smp_status VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS shop_record (
    sr_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    s_id INTEGER NOT NULL,
    sr_description VARCHAR(200) NOT NULL,
    sr_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS shop_unit (
    s_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    s_unit VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    s_startdatetime TIMESTAMP NOT NULL,
    s_enddatetime TIMESTAMP NOT NULL,
    s_remarks VARCHAR(200) NOT NULL,
    s_status VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_code (
    tc_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tc_code VARCHAR(12) NOT NULL,
    f_driverid VARCHAR(50) NOT NULL DEFAULT '',
    unit_name VARCHAR(200) NOT NULL DEFAULT '',
    tc_date TIMESTAMP NOT NULL,
    tc_status VARCHAR(20) NOT NULL DEFAULT 'Unused'
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_ticket_code ON ticket_code (tc_code);
CREATE INDEX IF NOT EXISTS idx_ticket_code_status ON ticket_code (tc_status);
CREATE INDEX IF NOT EXISTS idx_ticket_code_driver ON ticket_code (f_driverid);

CREATE TABLE IF NOT EXISTS trailer (
    trailer_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trailer_name VARCHAR(200) NOT NULL,
    trailer_plateno VARCHAR(200) NOT NULL,
    trailer_assignto VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    trailer_location VARCHAR(200) NOT NULL,
    trailer_status VARCHAR(200) NOT NULL,
    t_recordedby VARCHAR(200) NOT NULL,
    t_approvedby VARCHAR(200) NOT NULL,
    t_date TIMESTAMP NOT NULL,
    trailer_container VARCHAR(200) NOT NULL,
    trailer_remarks VARCHAR(200) NOT NULL,
    current_base VARCHAR(100) NOT NULL DEFAULT 'PTSI Base',
    current_base_updated_at TIMESTAMP DEFAULT NULL,
    maintenance_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_reason VARCHAR(200) NOT NULL DEFAULT '',
    maintenance_expected_return TIMESTAMP DEFAULT NULL,
    maintenance_blocked_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_trailer_block ON trailer (maintenance_blocked);

CREATE TABLE IF NOT EXISTS trailer_jackup (
    tj_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER DEFAULT NULL,
    trailer_code VARCHAR(50) NOT NULL,
    driver_id INTEGER NOT NULL,
    lat NUMERIC(10,7) DEFAULT NULL,
    lng NUMERIC(10,7) DEFAULT NULL,
    photo_path VARCHAR(255) NOT NULL DEFAULT '',
    detached_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP DEFAULT NULL,
    billing_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_tj_trailer ON trailer_jackup (trailer_code);
CREATE INDEX IF NOT EXISTS idx_tj_active ON trailer_jackup (billing_active);

CREATE TABLE IF NOT EXISTS trailer_movement (
    tm_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tm_trailername VARCHAR(200) NOT NULL,
    tm_trailer_status VARCHAR(200) NOT NULL,
    tm_driverassign VARCHAR(200) NOT NULL,
    tm_location VARCHAR(200) NOT NULL,
    tm_recordedtype VARCHAR(200) NOT NULL,
    tm_recordedby VARCHAR(200) NOT NULL,
    tm_approvedby VARCHAR(200) NOT NULL,
    tm_date TIMESTAMP NOT NULL,
    tm_container VARCHAR(200) NOT NULL,
    tm_remarks VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS trailer_transaction (
    t_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    t_datetime TIMESTAMP NOT NULL,
    t_location VARCHAR(200) NOT NULL,
    t_truck VARCHAR(200) NOT NULL,
    t_genset VARCHAR(200) NOT NULL,
    t_driver VARCHAR(200) NOT NULL,
    t_status VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS trips (
    trip_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER NOT NULL,
    trip_type VARCHAR(200) NOT NULL,
    trip_trailer VARCHAR(200) NOT NULL,
    trip_genset VARCHAR(200) NOT NULL,
    costumer VARCHAR(200) NOT NULL,
    segment_costumer VARCHAR(200) NOT NULL DEFAULT '',
    trip_containertype VARCHAR(200) NOT NULL,
    trip_container VARCHAR(200) NOT NULL,
    container_activity VARCHAR(200) NOT NULL,
    trip_containerstat VARCHAR(200) NOT NULL,
    trip_haulingsegment VARCHAR(200) NOT NULL,
    trip_haulingtype VARCHAR(200) NOT NULL,
    trip_from VARCHAR(200) NOT NULL,
    trip_to VARCHAR(200) NOT NULL,
    return_location VARCHAR(200) NOT NULL,
    km_run VARCHAR(200) NOT NULL,
    trip_departuredatetime TIMESTAMP NOT NULL,
    trip_arrivaldatetime TIMESTAMP NOT NULL,
    trip_pharrivaldatetime TIMESTAMP NOT NULL,
    deliver_location VARCHAR(200) NOT NULL,
    deliver_datetime TIMESTAMP NOT NULL,
    withdraw_location VARCHAR(200) NOT NULL,
    withdraw_datetime TIMESTAMP NOT NULL,
    required_date DATE NOT NULL,
    trip_status VARCHAR(200) NOT NULL,
    segment_status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    remarks VARCHAR(200) NOT NULL,
    foul_trip BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled_at TIMESTAMP DEFAULT NULL,
    cancelled_reason VARCHAR(255) NOT NULL DEFAULT '',
    scheduled_at TIMESTAMP DEFAULT NULL,
    -- Multi-leg trip ticket — per-leg run order (1-based) for the printed ticket.
    -- The booking leg keeps trip_type = 'Trip 1'; trip_seq lets the ticket render
    -- legs in the dispatcher's dragged order even when the booking leg isn't first.
    trip_seq INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS d_id ON trips (d_id);

CREATE TABLE IF NOT EXISTS trip_receipts (
    receipts_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tc_id INTEGER NOT NULL DEFAULT 0,
    control_no VARCHAR(255) NOT NULL DEFAULT '',
    tr_number VARCHAR(100) NOT NULL DEFAULT '',
    location_from VARCHAR(200) NOT NULL DEFAULT '',
    location_to VARCHAR(200) NOT NULL DEFAULT '',
    total_km NUMERIC(11,2) NOT NULL DEFAULT 0.00,
    maptotal_kmrun NUMERIC(11,2) NOT NULL DEFAULT 0.00
);
CREATE INDEX IF NOT EXISTS idx_trip_receipts_tc ON trip_receipts (tc_id);
CREATE INDEX IF NOT EXISTS idx_trip_receipts_control ON trip_receipts (control_no);

CREATE TABLE IF NOT EXISTS units (
    unit_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    unit_name VARCHAR(200) NOT NULL,
    unit_type VARCHAR(20) NOT NULL DEFAULT 'truck',
    unit_plate VARCHAR(200) NOT NULL,
    unit_address VARCHAR(200) NOT NULL,
    unit_assign VARCHAR(200) NOT NULL,
    driver_id INTEGER NOT NULL,
    unit_assigngenset VARCHAR(200) NOT NULL,
    unit_assigntrailer VARCHAR(200) NOT NULL,
    unit_std NUMERIC(11,2) NOT NULL,
    unit_status VARCHAR(200) NOT NULL,
    unit_or VARCHAR(200) NOT NULL,
    unit_cr VARCHAR(200) NOT NULL,
    unit_brand VARCHAR(200) NOT NULL,
    unit_modal VARCHAR(200) NOT NULL,
    unit_year VARCHAR(200) NOT NULL,
    unit_engineno VARCHAR(200) NOT NULL,
    unit_chassisno VARCHAR(200) NOT NULL,
    unit_fueltype VARCHAR(200) NOT NULL,
    unit_capacity VARCHAR(200) NOT NULL,
    unit_remarks VARCHAR(200) NOT NULL,
    unit_frontview VARCHAR(200) NOT NULL,
    unit_leftview VARCHAR(200) NOT NULL,
    unit_rightview VARCHAR(200) NOT NULL,
    unit_backview VARCHAR(200) NOT NULL,
    unit_assignsegment VARCHAR(200) NOT NULL,
    current_location VARCHAR(100) NOT NULL DEFAULT 'PTSI Base',
    current_location_updated_at TIMESTAMP DEFAULT NULL,
    maintenance_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    maintenance_reason VARCHAR(200) NOT NULL DEFAULT '',
    maintenance_expected_return TIMESTAMP DEFAULT NULL,
    maintenance_blocked_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_units_type ON units (unit_type);
CREATE INDEX IF NOT EXISTS idx_units_block ON units (maintenance_blocked);

CREATE TABLE IF NOT EXISTS unit_maintenance (
    um_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    unit_kind VARCHAR(20) NOT NULL,
    unit_code VARCHAR(50) NOT NULL,
    category VARCHAR(40) NOT NULL DEFAULT 'other',
    severity VARCHAR(20) NOT NULL DEFAULT 'med',
    reason VARCHAR(500) NOT NULL DEFAULT '',
    photo_path VARCHAR(255) NOT NULL DEFAULT '',
    expected_return TIMESTAMP DEFAULT NULL,
    scheduled_start_at TIMESTAMP DEFAULT NULL,
    activated_at TIMESTAMP DEFAULT NULL,
    blocked_by INTEGER DEFAULT NULL,
    blocked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_by INTEGER DEFAULT NULL,
    released_at TIMESTAMP DEFAULT NULL,
    release_notes VARCHAR(500) NOT NULL DEFAULT '',
    cost_labor NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    cost_parts NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
);
CREATE INDEX IF NOT EXISTS idx_um_kind_code_status ON unit_maintenance (unit_kind, unit_code, status);
CREATE INDEX IF NOT EXISTS idx_um_status ON unit_maintenance (status);

CREATE TABLE IF NOT EXISTS update_log (
    log_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    f_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    uplog_datetime TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_update_log_fid ON update_log (f_id);

CREATE TABLE IF NOT EXISTS "user" (
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    user_fname VARCHAR(255) NOT NULL,
    user_lname VARCHAR(255) NOT NULL,
    user_mname VARCHAR(1) NOT NULL,
    user_assignlocation VARCHAR(200) NOT NULL,
    customer_code VARCHAR(100) NOT NULL DEFAULT '',
    user_email VARCHAR(255) NOT NULL,
    user_pass VARCHAR(255) NOT NULL,
    user_type VARCHAR(255) NOT NULL,
    user_image VARCHAR(255) NOT NULL,
    user_accountstat VARCHAR(200) NOT NULL,
    user_code INTEGER NOT NULL DEFAULT 0,
    microsoft_oid VARCHAR(64) NOT NULL DEFAULT '',
    microsoft_tenant_id VARCHAR(64) NOT NULL DEFAULT '',
    microsoft_email VARCHAR(255) NOT NULL DEFAULT '',
    microsoft_linked_at TIMESTAMP DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_ms_oid ON "user" (microsoft_oid);
CREATE INDEX IF NOT EXISTS idx_user_customer_code ON "user" (customer_code);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMP NULL DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (email);

CREATE TABLE IF NOT EXISTS violation_record (
    vr_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    driver_id INTEGER NOT NULL,
    vr_type VARCHAR(200) NOT NULL,
    vr_description VARCHAR(200) NOT NULL,
    vr_status VARCHAR(200) NOT NULL,
    vr_recordedby INTEGER NOT NULL,
    vr_date DATE NOT NULL,
    vr_done_date DATE NOT NULL,
    -- When set, the violation is scheduled: it stays vr_status='Scheduled' and
    -- the driver is only blocked once this timestamp is reached (auto-activated).
    vr_scheduled_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS workflow_event (
    we_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    d_id INTEGER DEFAULT NULL,
    booking_no VARCHAR(200) NOT NULL DEFAULT '',
    stage VARCHAR(40) NOT NULL,
    actor_role VARCHAR(20) NOT NULL DEFAULT '',
    actor_id INTEGER DEFAULT NULL,
    notes VARCHAR(500) NOT NULL DEFAULT '',
    event_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_we_dispatch ON workflow_event (d_id, event_at);
CREATE INDEX IF NOT EXISTS idx_we_booking ON workflow_event (booking_no, event_at);

