-- =====================================================================
-- 030 — Geotab integration, Phase 2: geofences (zone arrival/departure).
--
-- We sync Geotab Zones (polygons) into geotab_zone, then the poller decides
-- which zone each linked truck is in from the position it already pulls
-- (point-in-polygon) — no dependency on MyGeotab Rules being configured.
--
-- Zone entry/exit is logged to geotab_zone_event and the truck's current zone
-- is tracked on `units`. On entry we also refresh units.current_location (the
-- free-text location the app already shows) to the zone name, so existing
-- views get hardware-verified location for free.
--
-- Additive & idempotent (§10). Lowercase identifiers.
-- =====================================================================

-- Local cache of Geotab zones + what each one means to us.
CREATE TABLE IF NOT EXISTS geotab_zone (
    zone_id     VARCHAR(50) PRIMARY KEY,   -- Geotab Zone.id
    name        VARCHAR(200) NOT NULL DEFAULT '',
    -- Our classification, set on the admin zones page:
    -- 'base' | 'gate' | 'customer' | 'other'. Drives arrival semantics.
    kind        VARCHAR(20)  NOT NULL DEFAULT 'other',
    -- Polygon vertices as JSON: [{"lat":..,"lng":..}, ...].
    points      JSONB        NOT NULL DEFAULT '[]',
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    synced_at   TIMESTAMP    NULL
);
CREATE INDEX IF NOT EXISTS idx_geotab_zone_active ON geotab_zone (active);
CREATE INDEX IF NOT EXISTS idx_geotab_zone_kind   ON geotab_zone (kind);

-- Current-zone state on each unit.
ALTER TABLE units
    ADD COLUMN IF NOT EXISTS current_zone_id VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS zone_entered_at TIMESTAMP   NULL;

-- Arrival/departure log.
CREATE TABLE IF NOT EXISTS geotab_zone_event (
    gze_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id     INTEGER      NOT NULL,
    unit_name   VARCHAR(200) NOT NULL DEFAULT '',
    zone_id     VARCHAR(50)  NOT NULL,
    zone_name   VARCHAR(200) NOT NULL DEFAULT '',
    zone_kind   VARCHAR(20)  NOT NULL DEFAULT 'other',
    event       VARCHAR(10)  NOT NULL,      -- 'entry' | 'exit'
    lat         NUMERIC(10,7) NULL,
    lng         NUMERIC(10,7) NULL,
    occurred_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_geotab_zone_event_unit ON geotab_zone_event (unit_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_geotab_zone_event_zone ON geotab_zone_event (zone_id, occurred_at DESC);
