-- =====================================================================
-- 032 — Geotab integration, Phase 4: fuel reconciliation.
--
-- Cross-checks each Gastender fuel ticket (fuel_report) against Geotab's
-- engine-measured fuel used and distance over the same interval (previous
-- ticket -> this ticket, per unit). A large positive liters variance
-- (dispensed >> engine burned) is a shrinkage/theft flag; a km variance
-- flags odometer/hubo manipulation.
--
-- Populated by php/operations/geotab_reconcile_fuel.php (batch, ~daily).
-- Surfaced read-only in admin/fuel-reconciliation.php.
--
-- Additive & idempotent (§10). Lowercase identifiers.
-- =====================================================================

CREATE TABLE IF NOT EXISTS fuel_reconciliation (
    fr_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_id             INTEGER      NOT NULL,               -- fuel_report.f_id
    unit_name        VARCHAR(200) NOT NULL DEFAULT '',
    device_id        VARCHAR(50)  NOT NULL DEFAULT '',
    period_start     TIMESTAMP    NULL,                   -- previous ticket time
    period_end       TIMESTAMP    NULL,                   -- this ticket time
    ticket_liters    NUMERIC(11,2) NULL,
    geotab_liters    NUMERIC(11,2) NULL,
    liters_variance  NUMERIC(11,2) NULL,                  -- ticket - geotab
    ticket_km        NUMERIC(11,2) NULL,
    geotab_km        NUMERIC(11,2) NULL,
    km_variance      NUMERIC(11,2) NULL,                  -- ticket - geotab
    -- 'ok' | 'liters_flag' | 'km_flag' | 'no_data'
    flag             VARCHAR(20)  NOT NULL DEFAULT 'no_data',
    computed_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fuel_reconciliation_fid UNIQUE (f_id)
);
CREATE INDEX IF NOT EXISTS idx_fuel_recon_unit ON fuel_reconciliation (unit_name);
CREATE INDEX IF NOT EXISTS idx_fuel_recon_flag ON fuel_reconciliation (flag);
