<?php
// Lightweight user activity log. Records logins and high-value actions into a
// dedicated activity_log table. The admin Activity Log viewer merges this with
// the existing workflow_event audit into one timeline.
//
// Logging is best-effort: pt_log_activity() never throws, so a logging failure
// can't break the action being logged.

require_once __DIR__ . '/../config/config.php';

if (!function_exists('pt_ensure_activity_log_table')) {
    function pt_ensure_activity_log_table(PDO $conn): void {
        static $ensured = false;
        if ($ensured) {
            return;
        }
        $conn->exec(
            "CREATE TABLE IF NOT EXISTS activity_log (
                al_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id    INTEGER       NULL,
                user_role  VARCHAR(40)   NOT NULL DEFAULT '',
                user_name  VARCHAR(160)  NOT NULL DEFAULT '',
                action     VARCHAR(120)  NOT NULL DEFAULT '',
                details    VARCHAR(500)  NOT NULL DEFAULT '',
                ip_address VARCHAR(64)   NOT NULL DEFAULT '',
                created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
            )"
        );
        $conn->exec("CREATE INDEX IF NOT EXISTS idx_activity_log_created ON activity_log (created_at)");
        $conn->exec("CREATE INDEX IF NOT EXISTS idx_activity_log_user ON activity_log (user_id)");
        pt_mark_table_exists('activity_log', true);
        $ensured = true;
    }
}

if (!function_exists('pt_log_activity')) {
    /**
     * Record one activity row. Best-effort — swallows any error.
     *
     * @param int|null $userId  The user/driver id (may be null for anonymous).
     * @param string   $role    Role label ('Admin', 'Dispatcher', 'Driver', …).
     * @param string   $name    Display name of the actor.
     * @param string   $action  Short action label ('Login', 'Assigned booking', …).
     * @param string   $details Optional extra context.
     * @param string|null $ip   Optional IP; defaults to REMOTE_ADDR.
     */
    function pt_log_activity(PDO $conn, ?int $userId, string $role, string $name, string $action, string $details = '', ?string $ip = null): void {
        try {
            pt_ensure_activity_log_table($conn);
            if ($ip === null) {
                $ip = (string)($_SERVER['REMOTE_ADDR'] ?? '');
            }
            $stmt = $conn->prepare(
                "INSERT INTO activity_log (user_id, user_role, user_name, action, details, ip_address)
                 VALUES (?, ?, ?, ?, ?, ?)"
            );
            $stmt->execute([
                ($userId !== null && $userId > 0) ? $userId : null,
                mb_substr($role, 0, 40),
                mb_substr($name, 0, 160),
                mb_substr($action, 0, 120),
                mb_substr($details, 0, 500),
                mb_substr($ip, 0, 64),
            ]);
        } catch (Throwable $e) {
            // Never let logging break the caller.
        }
    }
}
